### ISSUE TITLE
arnun ݨ support

### ISSUE THREAD

**Issue by bgo-eiu** [aliftype/hussaini-nastaleeq#2]
This request is for arnun ݨ support; it seems like this is the only letter of the Saraiki alphabet missing

**Comment by mpQadir** [comment]
The two letter of Saraiki Alphabet  are missing. It is requested that  Arnun ݨ and Waddi Daal ݙ be added please.

**Comment by khaledhosny** [comment]
This project is not actively maintained, I suggest using a different font.
