### ISSUE TITLE
Line Height issue 

### ISSUE THREAD

**Issue by Gaazi** [aliftype/hussaini-nastaleeq#4]
Assalamualaikum
Mashallah
It's Best Nastaliq font
For more better fix line Hieght issue 
![Screenshot_20231112-155240](https://github.com/aliftype/hussaini-nastaleeq/assets/69299500/ba64ca70-84ec-4a06-a8db-b4dbcbfc57de)

**Comment by khaledhosny** [comment]
This project is not actively maintained, I suggest setting the line height manually for now or using a different font.
